### ISSUE TITLE
Scroll bar persists on text and script files that aren't supposed to have them and crashes the program

### ISSUE THREAD

**Issue by minigameroom** [PlatinumMaster/SwissArmyKnife#7]
If, in the script or text editors, you scroll down in any file that lets you scroll down (such as game text file 63 or script file 10), then switch to a text or script file that does _not_ let you scroll down (such as game text file 65 or script file 4), the scroll bar will still be there, and if you pull it all the way up the program crashes.

I can only verify this happening on Windows, but this issue seems to be a bug with how the program renders text documents and does not discriminate by base ROM. (The examples above were tested with White 2)

**Comment by PlatinumMaster** [comment]
Solved this by giving every script instance its own TextDocument, per the new tabular workflow in the upcoming update.
