### ISSUE TITLE
Struggling with opening ROMs in app

### ISSUE THREAD

**Issue by Krishy2007** [PlatinumMaster/SwissArmyKnife#8]
Whenever I try creating a new project, I get an initialization error saying "File not found: BaseROMs/Black 2.nds".  I created a BaseROM folder with the Rom in multiple different directories but that didn't work. What am I supposed to do and where am I supposed to put the file? I couldn't find anything online about this so I'm asking here. I'm sorry if this is a dumb question and thanks in advance.

**Comment by PlatinumMaster** [comment]
Hi,

Do you have file extensions on? Check if the file isn't named `Black 2.nds.nds` first.

**Comment by Krishy2007** [comment]
> Hi,
> 
> Do you have file extensions on? Check if the file isn't named `Black 2.nds.nds` first.

I have file extensions on, I checked.

**Comment by PlatinumMaster** [comment]
Where is your BaseROMs folder? It should be in the same directory as the SwissArmyKnife executable.

**Comment by Krishy2007** [comment]
> Where is your BaseROMs folder? It should be in the same directory as the SwissArmyKnife executable.

The folder is in the same location as the SAK visual studio project file, if that's what you mean

**Comment by PlatinumMaster** [comment]
It should not be there. It should be in the same folder as `SwissArmyKnife.exe` (or, other platform dependent binary).

**Comment by PlatinumMaster** [comment]
Going to assume this is resolved, as this has not seen activity in almost a year.
